from flask import Flask, request, render_template_string, redirect, url_for
import os

app = Flask(__name__)

# Store the latest HTML content in memory
latest_html = "<h1>No HTML generated yet!</h1>"

# API endpoint to generate dynamic HTML
@app.route('/generate', methods=['POST'])
def generate_html():
    global latest_html
    data = request.json or {}
    
    latest_html = f"""
    <html>
        <head>
            <title>{data.get('title', 'Dynamic Page')}</title>
        </head>
        <body>
            <h1>{data.get('heading', 'Hello World')}</h1>
            <p>{data.get('content', 'This HTML is dynamically generated by Python!')}</p>
        </body>
    </html>
    """
    
    return {"message": "HTML generated successfully!", "view_url": "/latest"}

# Route to view the latest generated HTML
@app.route('/latest')
def view_latest():
    global latest_html
    return render_template_string(latest_html)

# Optional home page
@app.route('/')
def home():
    return "<h1>Dynamic HTML API is running! Use /generate to create HTML.</h1>"

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
